language: python

python: 
  - "2.7"
  - "3.4"
  
install:
    - pip install pyneuroml
    - pip install tables
    - pip install . 
    
script:
    
    # Basic test
    - cd examples
    - python Example2.py # test one example...
    - cd ..
    
    
    # Only run OMV tests on Python 2 (for now)
    - if [ ${TRAVIS_PYTHON_VERSION:O:1} == "3" ]; then exit 0 ; fi
    
    - pip install git+https://github.com/OpenSourceBrain/osb-model-validation
    - omv install PyNN
    
    - omv all -V
    - omv list-engines
