language: python

python: 
  - "2.7"
  - "3.4"
  
install:
    - pip install pyneuroml
    - pip install tables
    - pip install . 
    
script:
    - ls -alt
    - cd examples
    - python Example2.py
    - cd ..
