[metadata]
name = neuromllite
version = 0.6.1
author = Padraig Gleeson
author_email = p.gleeson@gmail.com
url = https://github.com/NeuroML/NeuroMLlit
license = LGPL-3.0-only
description = A common JSON/YAML based format for compact network specification, closely tied to NeuroML v2
long_description = file: README.md
long_description_content_type = text/markdown
classifiers =
    Intended Audience :: Science/Research
    Natural Language :: English
    Operating System :: OS Independent
    Programming Language :: Python :: 3.9
    Programming Language :: Python :: 3.10
    Programming Language :: Python :: 3.11
    Programming Language :: Python :: 3.12
    Programming Language :: Python :: 3.13
    Topic :: Scientific/Engineering

[options]
install_requires =
    libNeuroML>=0.5.1
    pyyaml
    numpy
    tables
    h5py
    modelspec>=0.2.6
    ppft[dill]

packages = find:

[options.packages.find]
include =
    neuromllite
    neuromllite.sweep
    neuromllite.gui

[options.entry_points]
console_scripts =
    nmllite-ui = neuromllite.gui.NMLliteUI:main

[options.extras_require]
extras =
    pyNN
    bmtk
    matplotlib
    PyQt5
    pyneuroml
    pyelectro
    neuron
    h5py
    graphviz


all =
    neuromllite[extras]

dev =
    neuromllite[all]
    neuromllite[doc]
    pytest
    pytest-xdist
    pre-commit
    ruff 


doc =
    sphinxcontrib-bibtex
    #pyNN
    bmtk
    matplotlib
    PyQt5
    pyneuroml
    pyelectro
    numpy
    neuron
    h5py
    graphviz
    pylems
    tables
    arbor==0.9.0

[flake8]
extend-ignore = E501, E502, F403, F405, W503, W504
